config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', :to => 'course_modules#index', :as => :index
  get '/login', :to => 'auth#login_form'
  get '/register', :to => 'auth#login_form'
  post '/register', :to => 'auth#register'
  post '/login', :to => 'auth#login'
  delete '/logout', :to => 'auth#logout'

  resources :course_modules, :except => [:edit, :new] do
    get '/', :to  => 'course_modules#index'
    get '/details', :to => 'course_modules#show', :as => :show
    
    resources :courseworks, :except => [:show, :edit, :new] do
      get '/', :to => 'courseworks#index'
      post '/submit_code_solution', :to => 'marking#submit_code_solution'
      post '/submit_code_tests', :to => 'marking#submit_code_tests'
      post '/submit_textual_solution', :to => 'marking#submit_textual_solution'
      get '/marked_code', :to => 'marking#marked_code'
      get '/marked_text', :to => 'marking#marked_text'

      nested do
        scope 'chatbot', :as => 'chatbot' do
          get '/', :to => 'chatbot#index'
          get '/find_answer', :to => 'chatbot#find_answer'
          get '/greet', :to => 'chatbot#greet'
          get '/new_question', :to => 'chatbot#new_question'
          
          resources :faqs, :except => [:show, :edit, :new] do
            get '/', :to => 'faqs#index'
          end
        end
      end
    end
  end
end

app/models/course_module.rb
class CourseModule < ApplicationRecord
  has_many :courseworks

  validates :name, :uniqueness => true, :presence => true, :allow_nil => false
  validates :lecturer_id, :presence => true, :allow_nil => false

  def lecturer
    @lecturer ||= User.find_by(:lecturer_id => lecturer_id)
  end

  def lecturer=(lecturer)
    @lecturer = lecturer
    self.lecturer_id = lecturer.lecturer_id
  end
end

app/controllers/course_modules_controller.rb
class CourseModulesController < ApplicationController
  before_action :set_breadcrumbs
  before_action :set_course_module, :only => [:update, :destroy]
  before_action :restrict_to_lecturer, :only => [:create]
  before_action :only => [:update, :destroy] do
    restrict_to_lecturer(@course_module.lecturer.lecturer_id)
  end

  def index
    @course_modules = CourseModule.order(:name => :asc)

    @new_course_module = CourseModule.new
    @new_course_module.lecturer = current_user
  end

  def show
    @course_module = CourseModule.find(params[:course_module_id])
  end

  def create
    @course_modules = CourseModule.order(:name => :asc)

    @new_course_module = CourseModule.new(course_module_params)
    @new_course_module.lecturer = current_user

    if @new_course_module.save
      redirect_to course_modules_url, notice: 'Module was successfully created.'
    else
      render :index
    end
  end

  def update
    if @course_module.update(course_module_params)
      redirect_to course_modules_url, notice: 'Module was successfully updated.'
    else
      @course_modules = CourseModule.order(:name => :asc).to_a
      @course_modules.map! do |course_module|
        if course_module.id == @course_module.id
          @course_module.name = course_module.name
          @course_module
        else
          course_module
        end
      end

      @new_course_module = CourseModule.new
      @new_course_module.lecturer = current_user

      render :index
    end
  end

  def destroy
    @course_module.destroy
    redirect_to course_modules_url, notice: 'Module was successfully destroyed.'
  end

  private
    def set_course_module
      if params[:id].blank?
        @course_module = current_user.course_modules.find(params[:course_module_id])
      elsif params[:course_module_id].blank?
        @course_module = current_user.course_modules.find(params[:id])
      end
    end

    def set_breadcrumbs
      @breadcrumbs = [
        { :name => 'Modules', :url => course_modules_path }
      ]
    end

    def course_module_params
      params.require(:course_module).permit(:name, :lecturer_id)
    end
end

app/views/course_modules/_edit_form_fields.html.erb
<% if course_module.errors.any? %>
  <ul data-target="course-modules.editError" data-object-id="<%= course_module.id %>" class="errors hide">
    <% course_module.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div
  class="input-field hide"
  data-target="course-modules.name"
  data-object-id="<%= course_module.id %>">
    <%= form.label :name %>
    <%= form.text_field :name, :id => "course_module_name_#{course_module.id}" %>
</div>

app/views/course_modules/_edit_form_submission.html.erb
<%=
  form.submit 'Update!',
  :class => 'btn waves-effect waves-light yellow darken-1 hide',
  :data => {
    :target => 'course-modules.updateButton',
    'object-id' => course_module.id,
    :action => 'click->course-modules#submitEditForm'
  }
%>

<a
  class="btn waves-effect waves-light red lighten-1 hide"
  data-object-id="<%= course_module.id %>"
  data-action="click->course-modules#hideEditForm">Cancel</a>

app/views/course_modules/_form_modal.html.erb
<div id="<%= modal_id %>" data-target="course-modules.modal" class="modal">
  <%= form_for new_course_module do |form| %>
    <div class="modal-content">
      <div class="row">
        <h4 class="col s12">New Module</h4>

        <% if new_course_module.errors.any? %>
          <ul data-target="course-modules.newError" class="col s12 errors">
            <% new_course_module.errors.full_messages.each do |message| %>
              <li class="error-message"><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="input-field col s12">
          <%= form.label :name %>
          <%= form.text_field :name, :id => :course_module_name %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%=
        form.submit 'Create!',
        :class => 'btn waves-effect waves-light'
      %>
      <a class="modal-action modal-close waves-effect waves-light red lighten-1 btn">Cancel</a>
    </div>
  <% end %>
</div>

app/views/course_modules/_table.html.erb
<table class="highlight">
  <tbody>
    <% course_modules.each do |course_module| %>
      <tr>
        <%=
          form_for(
            course_module,
            :data => {
              :target => 'course-modules.editForm',
              'object-id' => course_module.id
            }
          ) do |form|
        %>
          <td>
            <h5>
              <%= link_to course_module.name, course_module_courseworks_path(course_module) %>
            </h5>

            <%= render 'edit_form_fields', :course_module => course_module, :form => form %>
          </td>
          
          <% if current_user.lecturer_id == course_module.lecturer.lecturer_id %>
            <td class="right-align">
              <a
                class="btn-floating btn-large waves-effect waves-light yellow darken-1"
                data-action="click->course-modules#displayEditForm"
                data-object-id="<%= course_module.id %>">
                  <i class="material-icons">edit</i>
              </a>

              <%=
                link_to(
                  raw('<i class="material-icons">delete</i>'),
                  course_module,
                  :method => :delete,
                  :data => {
                    :confirm => 'Are you sure?',
                  },
                  :class => 'btn-floating btn-large waves-effect waves-light red lighten-1'
                )
              %>

              <%= render 'edit_form_submission', :course_module => course_module, :form => form %>
            </td>
          <% elsif !current_user.lecturer_id.blank? %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/course_modules/index.html.erb
<div
  id="course_modules_index"
  data-controller="course-modules"
  data-course-modules-notice="<%= notice %>">
    <h4>Modules</h>

    <%= render 'table', :course_modules => @course_modules, :current_user => @current_user %>

    <br>

    <% if @current_user.lecturer? %>
      <div class="fixed-action-btn">
        <%= 
          link_to(
            raw('<i class="material-icons">add</i>'),
            '#new-modal',
            :class => 'create-btn btn-floating btn-large waves-effect waves-light modal-trigger',
          )
        %>
      </div>

      <%= render 'form_modal', :modal_id => 'new-modal', :new_course_module => @new_course_module %>
    <% end %>
</div>